### ISSUE TITLE
Dependencies and use help

### ISSUE THREAD

**Issue by tliyan127** [connorcoley/retrosim#2]
Hi, i was trying to use retrosim and I did not find info on what to install and also any example scripts for testing. Is there a way you can help me with that. I am working on a windows machine using conda. Thanks

**Comment by tliyan127** [comment]
Hi, when i tried using "usable_model" and call "do_one('OC(Cn1cncn1)(Cn1cncn1)c1ccc(F)cc1F');", it gives me a error 'dict' object has no attribute 'iteritems'. I think this is related to test_similarity script. Can you tell me how to configure that file to work locally?

when i test process_results script, that i was able to change accordingly to work, This i am not sure how to do. Thanks

**Comment by connorcoley** [comment]
Hi @tliyan127 - the code was developed using Python 2. In Python 3, there is no longer a dict method called ```iteritems()```; replacing this with ```items()``` should probably be a sufficient fix.

**Comment by tliyan127** [comment]
Thanks, Anyway it still gives a lot more errors and i was not able to figure it out to work (probably on me), so no worries. Thanks
