### ISSUE TITLE
how to add and remove atom index?

### ISSUE THREAD

**Issue by chaoyan1037** [connorcoley/retrosim#5]
If I have a SMILES string like:
 `COC(=O)[C@H](CCCCN)NC(=O)Nc1cc(OC)cc(C(C)(C)C)c1O`,

How can I add atom indexs to convert the SMILES to string like :
`[NH2:1][CH2:2][CH2:3][CH2:4][CH2:5][C@@H:6]([C:7]([O:8][CH3:9])=[O:10])[NH:11][C:12](=[O:13])[NH:14][c:15]1[cH:16][c:17]([O:18][CH3:19])[cH:20][c:21]([C:22]([CH3:23])([CH3:24])[CH3:25])[c:26]1[OH:27]`

Also, if I have the latter one, how can I get the former one?
I have another dataset, and would like to run your model, I am not sure how to convert the data format.

**Comment by connorcoley** [comment]
Hi,

If you're using RDKit as your main cheminformatics toolkit, you can use the SetAtomMapNum and GetAtomMapNum methods of atom objects (e.g., https://www.rdkit.org/docs/source/rdkit.Chem.rdchem.html#rdkit.Chem.rdchem.Atom.SetAtomMapNum)

For example,
```
import rdkit.Chem as Chem 

smi = 'COC(=O)[C@H](CCCCN)NC(=O)Nc1cc(OC)cc(C(C)(C)C)c1O'
mol = Chem.MolFromSmiles(smi)
[a.SetAtomMapNum(i+1) for i,a in enumerate(mol.GetAtoms())]
print(Chem.MolToSmiles(mol))

smi = '[NH2:1][CH2:2][CH2:3][CH2:4][CH2:5][C@@H:6]([C:7]([O:8][CH3:9])=[O:10])[NH:11][C:12](=[O:13])[NH:14][c:15]1[cH:16][c:17]([O:18][CH3:19])[cH:20][c:21]([C:22]([CH3:23])([CH3:24])[CH3:25])[c:26]1[OH:27]'
mol = Chem.MolFromSmiles(smi)
[a.SetAtomMapNum(0) for a in mol.GetAtoms()]
print(Chem.MolToSmiles(mol))
```

**Comment by chaoyan1037** [comment]
Hi Connor,

Thanks for your kind reply! You solution works perfectly as I want.
One more question, how can I align atom index between reactants and products?

For example,
I have:
`
COC(=O)[C@H](CCCCNC(=O)OCc1ccccc1)NC(=O)Nc1cc(OC)cc(C(C)(C)C)c1O>>COC(=O)[C@H](CCCCN)NC(=O)Nc1cc(OC)cc(C(C)(C)C)c1O
`

I can get:
`
[O:1]=[C:2]([O:3][CH2:4][c:5]1[cH:6][cH:7][cH:8][cH:9][cH:10]1)[NH:11][CH2:12][CH2:13][CH2:14][CH2:15][C@@H:16]([C:17]([O:18][CH3:19])=[O:20])[NH:21][C:22](=[O:23])[NH:24][c:25]1[cH:26][c:27]([O:28][CH3:29])[cH:30][c:31]([C:32]([CH3:33])([CH3:34])[CH3:35])[c:36]1[OH:37]>>[NH2:1][CH2:2][CH2:3][CH2:4][CH2:5][C@@H:6]([C:7]([O:8][CH3:9])=[O:10])[NH:11][C:12](=[O:13])[NH:14][c:15]1[cH:16][c:17]([O:18][CH3:19])[cH:20][c:21]([C:22]([CH3:23])([CH3:24])[CH3:25])[c:26]1[OH:27]
` 

How can I get:
`
O=C(OCc1ccccc1)[NH:1][CH2:2][CH2:3][CH2:4][CH2:5][C@@H:6]([C:7]([O:8][CH3:9])=[O:10])[NH:11][C:12](=[O:13])[NH:14][c:15]1[cH:16][c:17]([O:18][CH3:19])[cH:20][c:21]([C:22]([CH3:23])([CH3:24])[CH3:25])[c:26]1[OH:27]>>[NH2:1][CH2:2][CH2:3][CH2:4][CH2:5][C@@H:6]([C:7]([O:8][CH3:9])=[O:10])[NH:11][C:12](=[O:13])[NH:14][c:15]1[cH:16][c:17]([O:18][CH3:19])[cH:20][c:21]([C:22]([CH3:23])([CH3:24])[CH3:25])[c:26]1[OH:27]
`

It seems like your dataset already has this mapping. But now I have a new dataset. I am not sure how to process it. Thanks a lot for any suggestions!

**Comment by connorcoley** [comment]
The process of assigning atom map numbers is called "atom mapping" or "atom-to-atom mapping". If you do a quick Google Scholar search, you'll see that there have been a number of algorithms and methods proposed over the years. None of them are perfect. A primer is here: https://www.nextmovesoftware.com/products/AtomMapping.pdf

If you're potentially interested in a commercial solution, I might suggest contacting NextMove Software about their NameRxn software. If you already have licenses to any of the following software (or can get a trial as an academic), you could look at ChemDraw's atom mapping, ChemAxon's, or PipelinePilot. A completely open-source implementation that was used for the original USPTO data is part of the Indigo toolkit (https://lifescience.opensource.epam.com/indigo/api/index.html).

**Comment by chaoyan1037** [comment]
Thanks a lot for your information! I wil give it a try. Apprecidated.
