### ISSUE TITLE
Fails to generate correct template in certain circumstances

### ISSUE THREAD

**Issue by loluwot** [connorcoley/retrosim#6]
For example, when using process_an_example, '[Cl:1][C:2]1=[C:9]([CH3:10])[CH:8]=[CH:7][C:4]([C:5]#[N:6])=[CH:3]1>>[Cl:1][C:2]1=[C:9]([CH2:10][Br:18])[CH:8]=[CH:7][C:4]([C:5]#[N:6])=[CH:3]1' gives: [CH3;D1;+0:1]-[c:2]>>[CH2;D2;+0:1]-[c:2] which seems to be incorrect.

**Comment by connorcoley** [comment]
That input SMILES string is not a valid one. Also, your reaction has the same reactant string as product string, so I don't know what you're trying to do
